### ISSUE TITLE
Error: Fetch a kernel repository following merge command

### ISSUE THREAD

**Issue by danghai** [RH-FMK/skt#82] opened 2018-04-20 02:21 UTC
Hello developers,
The skt project is really interesting. I followes the introduction from README to install and try some command option, but I am not sure why I got the error when I try to fetch a kernel repository following `merge` command. In particular, I try to run this command to checkout `master` branch of the `net-next` repo:
```
$ skt --rc skt-rc --state --workdir skt-workdir -vv \
         merge --baserepo git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git \
               --ref master
```

And then I got the error: 
```
2018-04-20 09:05:25,164    DEBUG   executing: git --work-tree skt-workdir --git-dir skt-workdir/.git fetch -n origin +master:refs/remotes/origin/master
fatal: unable to connect to git.kernel.org:
git.kernel.org[0: 147.75.58.133]: errno=Connection refused
git.kernel.org[1: 2604:1380:4020:600::1]: errno=Network is unreachable

Traceback (most recent call last):
  File "/usr/bin/skt", line 11, in <module>
    load_entry_point('skt', 'console_scripts', 'skt')()
  File "/home/danghai/skt/skt/executable.py", line 710, in main
    args.func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 116, in wrapper
    func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 137, in cmd_merge
    bhead = ktree.checkout()
  File "/home/danghai/skt/skt/__init__.py", line 291, in checkout
    self.git_cmd(*git_fetch_args)
  File "/home/danghai/skt/skt/__init__.py", line 189, in git_cmd
    subprocess.check_call(args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', '--work-tree', 'skt-workdir', '--git-dir', 'skt-workdir/.git', 'fetch', '-n', 'origin', '+master:refs/remotes/origin/master']' returned non-zero exit status 128
```

However, when I change the URL:  `https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git`, it is able to fetch. But it is frozen after completely fetch. I must terminate it . It shows:

```
2018-04-20 09:00:40,404    DEBUG   executing: git --work-tree skt-work --git-dir skt-work/.git fetch -n origin +master:refs/remotes/origin/master
remote: Counting objects: 5995556, done.
remote: Compressing objects: 100% (910905/910905), done.
remote: Total 5995556 (delta 5042858), reused 5992915 (delta 5041111)
Receiving objects: 100% (5995556/5995556), 1.01 GiB | 2.09 MiB/s, done.
Resolving deltas: 100% (5042858/5042858), done.
```

Could you help me handle these error?  Thanks

**Comment by veruu** [comment] 2018-04-20 08:40
Hi! The error you get in the first example is related to you network connection (`unable to connect to git.kernel.org, Network is unreachable`), not `skt`. Unstable network connection can actually lead to your second problem too, `git` was still waiting to receive the finishing touches from network. Checking out full kernel tree is pretty slow, combined with slower or unstable network it may appear as frozen for a while (happens to me a lot).

Both commands complete just fine for me. Can you verify that using a stable network?

**Comment by danghai** [comment] 2018-04-20 23:57
Thanks for response.
@spbnick Sorry what do you mean? I do not get it. 
@veruu. You are right. I use the public wifi in library. So, my network is not stable. It works fine when I use a stable network. Thanks

**Comment by veruu** [comment] 2018-04-21 00:16
Great news! Closing this as not caused by `skt` but don't hesitate to reach out if you have other issues related to it.

**Closed by veruu** 2018-04-21 00:16 UTC
